### ISSUE TITLE
FHD DBC control support

### ISSUE THREAD

**Issue by marchom** [grawlinson/dell-xps-9360#1]
Dell also [posted ](http://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=312K3) a newer version of the display control firmware for FHD with capability to disable DBC for it as well. Might want to update this to v 0.0.0.20.

**Comment by pachulo** [comment]
I uploaded it in PR https://github.com/grawlinson/dell-xps-9360/pull/5

**Comment by grawlinson** [comment]
Awesome, thanks! I'll update the repo when I get back from holiday next Tuesday.

**Comment by grawlinson** [comment]
Didn't realize I could merge from web.

Have accepted all PRs, will close this issue.

If there's anything else you'd like added, feel free to do so! 😊
