### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by ghost** [grawlinson/dell-xps-9360#11]
How does this differ from the Dell provided BIOS firmware, and why is the version different?

**Comment by grawlinson** [comment]
This _is_ the firmware for the XPS13, straight from Dell's website.

What do you mean when you say that the version is different?

**Comment by ghost** [comment]
https://www.dell.com/support/home/nz/en/nzdhs1/drivers/driversdetails?driverid=g05nr

Says vs 2.6.2

**Comment by jamesmayes** [comment]
Hello Kennedy,

Version 2.6.2 came out months ago. The latest from Dell is 2.9.0.

This repo tracks all releases in a more convenient way.

https://github.com/grawlinson/dell-xps-9360/tree/master/bios

**Comment by jamesmayes** [comment]
If you wish to confirm, you can always seek the same from Dell directly.
For instance, here is 2.9.0 at the Dell site.

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=rckdk

**Comment by ghost** [comment]
Hey, sorry.. the last time I visited the dell website they had a statement saying the older firmware was out of date so when it didn't say it on 2.6.2 i assumed it was their latest

**Comment by ghost** [comment]
I'm using linux, so the only firmware from this repo I want is the bios correct?

**Comment by grawlinson** [comment]
Yep! Depending on your distribution, you can use `fwupd` to do this. Here's the [docs](https://fwupd.org/users).

It's a matter of doing:

```shell
$ sudo fwupdmgr refresh # refreshes list of available updates
$ fwupdmgr get-updates  # check if updates are available
$ sudo fwupdmgr update  # installs update (must be connected to AC power)
```
